apiVersion: v1
kind: Service
metadata:
  name: conversation-service
  labels:
    app: conversation
spec:
  type: NodePort
  selector:
    app: conversation
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http

